### PR TITLE
Initial commit of validation changes for microservices

### PR DESCRIPTION
**Pull request by KieranFrance**

### CODE REVIEW

**Comment by KieranFrance** [comment]
@leonatherton Missing settings have been added. New validation method (compare string values to regex) has been included to handle all scaling values, page ranges, and values that can be any value provided by the user.

You will notice to catch any possible value provided by user I have used ".*". This should work if no new lines are present. Should allow for new lines, explicitly lock them out, handle better? Whats your opinion on this flag?

**Comment by leonatherton** [comment]
@KieranFrance I think .* is probably ok as-is.

For logicalPageRange and realPageRange, would those regexs actually match anything due to the wildcard at the end (which matches between 0 and unlimited times)?

I also spotted that content mode is allowing the viewerUI setting, however that is not a valid setting in content mode.

I am wondering if we should just do simple checking - i.e. checking that the setting exists and the value is valid for that setting.

Things can get complicated if we want to do context-based checking, e.g. outputThumbnails and generateSearchFile cannot be disabled when viewerUI=complete, and it's not possible to mix base64 fonts with non-base64 fonts.

**Comment by KieranFrance** [comment]
I have looked further into the settings validation.

You were correct on the page range expression, I have updated and tested, replacing the final * with a + fixed the issue.
I have also removed the contextual validation to remove complexity, this is an option we could revisit in the future.

**Comment by KieranFrance** [comment]
All settings are now validated without context (if a setting doesn't do anything for the specified view mode it can still validate).
I have also added updates to use the new base changes to return human-readable error messages.

**Pull request merged**
