### PR TITLE
Updated finalName to buildvu-microservice

### PR DESCRIPTION
**Pull request by EthanIDR**

### CODE REVIEW

**Comment by EthanIDR** [comment]
@daniel-warren - ok should I cancel this request and remake it when the other one os through or would it be better to just keep it here and then update it when ready?

**Comment by daniel-warren** [comment]
@EthanIDR  - I think it'd be simplest to keep it here and update when ready. 

FYI, you could add the version change to this PR and merge it first, but for https://github.com/idrsolutions/buildvu-microservice-example/pull/15 you would then need to update the version to 3.1.0-alpha. Though without @leonatherton's approval it's a rather moot point.

**Comment by leonatherton** [comment]
Sounds like a good plan to me

**Comment by EthanIDR** [comment]
@daniel-warren & @leonatherton  - I ave updated the version number here and caged the version umbe on #15, am I ok to merge

**Comment by leonatherton** [comment]
@EthanIDR I think this PR should increment the major version as it is a non-backwards compatible change. #15 would then update the minor version.

**Comment by daniel-warren** [comment]
@EthanIDR - I think I may not have been clear enough. My suggestion was that https://github.com/idrsolutions/buildvu-microservice-example/pull/15 kept it's version and was merged first. Now that you've updated it's version that might not be the simplest approach.

Whichever gets merged first, this pull request's version number should be 3.0.0-alpha. As @leonatherton says it's a non-backwards compatible change.

**Comment by EthanIDR** [comment]
@daniel-warren & @leonatherton - sorry misunderstood, should I merge this as 3.0.0 then merge #15 as 3.1.0 then?

**Comment by leonatherton** [comment]
@EthanIDR I think what Daniel is asking is that #15 should be version 2.3.0 and get merged first, then #17 should be 3.0.0 and get merged second. That sounds good to me.

**Comment by EthanIDR** [comment]
am I ok to resolve the conflict a merge this @daniel-warren @leonatherton

**Comment by daniel-warren** [comment]
@EthanIDR - I would wait for @leonatherton's approval of the PR first, If I recall correctly, resolving conflicts happens as part of the merge, so I'm unsure if after making the changes you'd be able to delay the merge with master.

**Pull request merged**
