### PR TITLE
Updated pom file to use new version of base-microservice-example

### PR DESCRIPTION
**Pull request by niraliabhani**
https://3.basecamp.com/3537281/buckets/4129302/todos/2034514413

### CODE REVIEW

**Comment by niraliabhani** [comment]
@leonatherton No some problem appears when I rebuild. 
Here also, I need to refractor conversion to com.idrsolutions.microservice.
Also, there seems to be import issue with BuildvuConverter (org.jpedal.examples.BuildvuConverter)class which I am unable to locate anywhere.
image

**Comment by leonatherton** [comment]
@niraliabhani You will need to use buildvu-svg.jar or buildvu-html.jar which has that class

**Comment by niraliabhani** [comment]
@Leon I have added two new commits. 
one query, should i have to chnage pom file to use buidvu-html to allow it to compile ?

**Comment by leonatherton** [comment]
@niraliabhani the package for BuildVuServlet needs to be com.idrsolutions.microservice

Would it be possible to update that today so that we can merge?

**Comment by niraliabhani** [comment]
@leonatherton I have updated . Apologies, I thought I had used that but somehow it was not used.

**Pull request merged**
