### PR TITLE
Updating version number of base servlet.

### PR DESCRIPTION
**Pull request by patricksheppard-IDR**
Base servlet version number has been updated. Should be pulled at the same time as base servlet PR #9

### CODE REVIEW

**Comment by RFoley** [comment]
@patricksheppard-IDR please could you update the API doc with the relevant details and attach it to this PR?

You'll want to mention:
- URL is an optional param
- An attached file takes priority (URL param will be ignored)
- Request only needs to be multipart if attaching a file
- Also update error message to "Missing file or URL"

**Comment by patricksheppard-IDR** [comment]
@RFoley Will update API when I get some time.

**Comment by patricksheppard-IDR** [comment]
Have added javadoc changes here to avoid merge conflicts and keep consistency with commits in base server.

**Comment by patricksheppard-IDR** [comment]
API doc is updated

**Comment by patricksheppard-IDR** [comment]
I have updated the buildvu server according to suggestion from @leonatherton in [this proposal](https://github.com/idrsolutions/base-microservice-example/blob/api-proposal/src/main/java/conversion/BaseServlet.java)

@leonatherton @RFoley @daniel-warren - Could you review and suggest anything that needs changing?

**Comment by patricksheppard-IDR** [comment]
That makes sense, I must not have read your suggestion properly, sorry about that.

**Comment by patricksheppard-IDR** [comment]
@leonatherton Have removed queue item

**Comment by leonatherton** [comment]
@patricksheppard-IDR please merge this in to master

**Pull request merged**
